### ISSUE TITLE
Exec in desktop file

### ISSUE THREAD

**Issue by GordonZed** [agx/phosh-osk-stub#1]
I'm trying to get this working on PostmarketOS. Thankfully, it turns out Alpine does in fact have dpkg, but while it did appear to install, it failed when it came to updating the desktop file.

Should I be using wvkbd-mobintl, or wvkbd-dbus? Or something else entirely?

I tried /usr/bin/wvkbd-dbus, but it caused on error on starting Phosh.

**Comment by agx** [comment]
Alpine has it packaged already: https://pkgs.alpinelinux.org/package/edge/community/x86_64/phosh-osk-stub

You don't need `dpkg` for the build, that is only for Debian packaging.  Please post the full error log at https://gitlab.gnome.org/guidog/phosh-osk-stub as this repo is only a mirror.
